### ISSUE TITLE
杂线

### ISSUE THREAD

**Issue by THISISAGOODNAME** [hozuki/Bulletproof#3]
用electron测试，发现pixi.js有大量杂线

**Comment by ghost** [comment]
问题似乎来源于pixi.js将多边形封口的行为，这个行为和Flash是不一致的

```
var s = $.createShape({
    lifeTime: 7
});
var g = s.graphics;
g.lineStyle(1, 0xFFFFFF);
g.moveTo(100, 100);
g.lineTo(200, 100);
g.lineTo(200, 200);
// pixi.js behaves as if this is uncommented:
// g.lineTo(100, 100);
```

EDIT: `_pixiGraphics.currentPath.shape.closed`属性显然控制了当前路径上的这一行为。这[看起来不是公开的API](http://pixijs.github.io/docs/PIXI.Polygon.html)，因此除去对pixi,js进行更改的方式，只能在每次`drawShape`调用后手动设置这一属性，并且这样做的其他后果是尚不明确的。

```
var s = $.createShape({
    lifeTime: 7
});
var g = s.graphics;
g.beginFill(0xFF0000);
g.lineStyle(1, 0xFFFFFF);
g.moveTo(100, 100); // this method calls Graphics#drawShape down the stack
g._pixiGraphics.currentPath.shape.closed = false;
g.lineTo(200, 100);
g.lineTo(200, 200);
g.endFill();
```

**Comment by hozuki** [comment]
感谢二位的反馈。
@akaza-akari 谢谢指引。简略翻了一下pixi的源代码，发现和 `math.Polygon` 创建有点关系。
当前用的是 [pixi.js-build-v3.0.7](//cdn.bootcss.com/pixi.js/3.0.7/pixi.js)。
追溯到 8784 行，和 7928 行，一部分的原因是会用 `Polygon` 作为标准的 `GraphicsData.shape` 来保存点数据，而查询得 `Polygon` 仅仅在实例化时对 `closed` 赋值为 `true`（10658 行）。当改变了这个初始值后绿坝娘和小圆脸的示例能正常工作了。这里举小圆脸的例子：
![image](https://cloud.githubusercontent.com/assets/7345875/10004445/4cb235ae-60e4-11e5-9e40-ee8c99ed19d4.png)
接下去有时间我会接着看看其他的原因是什么。这个时间点我先睡了，今天有一整天的课。

---

EDIT:
搜索了一下 Pixi 的 issue，能找到最开始反映的 pixijs/pixi.js#1892，的确有人抱怨说是 pixijs/pixi.js#1863 的倒退。尝试了一下，在 [pixi.js-build-v3.0.6](//cdn.bootcss.com/pixi.js/3.0.6/pixi.js) 时并没有这个问题，不修改任何代码的情况下 3.0.6 能正常运行示例2和3。
PS. 上述的“临时”方案和特性倒退对于三维球示例都不起作用。

**Comment by ghost** [comment]
@Hozuki 手机，没有实际测试，但只从那个PR的diff上看的话，3.0.6应该在有填充的情况下仍然存在问题。试试我上面回复的第二段代码（当然closed=false要去掉）。

pixijs/pixi.js#1892看起来死了，而且他们也有很多issue堆在那里。我们是否能做些什么？

**Comment by hozuki** [comment]
@akaza-akari 经过试验，情况有点有趣。

代码片段1：

``` javascript
var s = $.createShape({
    lifeTime: 8
});
var g = s.graphics;
g.lineStyle(1, 0xffffff);
g.moveTo(100, 100);
g.lineTo(200, 100);
g.lineTo(200, 200);
```

代码片段2：

``` javascript
var s = $.createShape({
    lifeTime: 7
});
var g = s.graphics;
g.beginFill(0xff0000);
g.lineStyle(1, 0xffffff);
g.moveTo(100, 100);
g._pixiGraphics.currentPath.shape.closed = false;
g.lineTo(200, 100);
g.lineTo(200, 200);
g.endFill();
```

测试1：Pixi.js v3.0.6 运行代码片段1
- 通过
- 期望结果：一条白色折线，不封口
- 实际结果：一条白色折线，不封口

测试2：Pixi.js v3.0.6 运行代码片段2
- 通过
- 期望结果：一条白色折线包围着一个红色三角形的两边，第三边没有白色线段
- 实际结果：一条白色折线包围着一个红色三角形的两边，第三边没有白色线段

测试3：Pixi.js v3.0.7 运行代码片段1

测试4：Pixi.js v3.0.7 运行代码片段2

测试3和测试4的结果分别与测试1和测试2相同。

但是加入曲线就开始乱套了。

代码片段3：

``` javascript
var s = $.createShape({
    lifeTime: 8
});
var g = s.graphics;
g.lineStyle(1, 0xffffff);
g.moveTo(100, 100);
g.lineTo(200, 100);
g.lineTo(200, 200);
g.curveTo(350, 125, 300, 400);
```
- 期望结果：一条白色折线连接着一条白色曲线，没有封口
- 实际结果：一条白色折线连接着一条白色的曲线，且_曲线部分_自动封口（从 (300,400) 到 (200,200)）

此时3.0.6和3.0.7行为相同。

我觉得可以设置 `Polyline` 类来解决这个问题，其主体和 `Polygon` 是一样的，只不过永远不封口。

Pixi 关于填充的做法是每次拐弯都会尝试封口填充（`closed = closed | isFill`），和 Flash、GDI 等的“先创建路径再统一填充”的做法不同。

一个做法是基于现有的 Pixi 改造……

**Comment by ghost** [comment]
@Hozuki 看起来是可行的。在`SHAPE`下增添一个常量，小改一下两个渲染器，应该就能达到“永远不封口”这个要求。值得一试。不过提到填充实现的方式，现在的测试代码中似乎没有[winding](https://en.wikipedia.org/wiki/Winding_number)相关的内容。如果不能正确画出winding，可能需要进行的改动就复杂很多了。因此有必要对此进行实验。

**Comment by hozuki** [comment]
@akaza-akari 带填充的时候更混乱了。

测试1：

![image](https://cloud.githubusercontent.com/assets/7345875/10052216/5018ea10-6258-11e5-8965-3e362b5ad80f.png)

``` javascript
g.beginFill(0xff0000, 0.4);
g.lineStyle(1, 0xffffff);
g.moveTo(100, 100);
g._pixiGraphics.currentPath.shape.closed = false;
g.lineTo(200, 100);
g.lineTo(200, 200);
g.curveTo(350, 125, 300, 400);
g.lineTo(180, 120);
g.endFill();
```

测试2：

![image](https://cloud.githubusercontent.com/assets/7345875/10052180/1f843a94-6258-11e5-86aa-2e8ebba9cbf5.png)

``` javascript
g.beginFill(0xff0000, 0.4);
g.lineStyle(1, 0xffffff);
g.moveTo(100, 100);
g._pixiGraphics.currentPath.shape.closed = false;
g.lineTo(200, 100);
g.lineTo(200, 200);
g.curveTo(350, 125, 300, 400);
g.lineStyle(3, 0x0000ff);
g.lineTo(180, 120);
g.endFill();
```

可以注意到，`closed` 只控制了线条的闭合状态。测试1中神奇的填充区域没想出是怎么来的，即使曲线分了段也不该在中间只引出一个点吧。测试2由于设置了 `lineStyle` 所以立即flush掉要绘制的数据。

Pixi 的三角形生成（`/src/core/graphics/webgl/GraphicsRenderer.js`）由 [earcut](//github.com/mapbox/earcut) 完成，没有给出任何的孔（孔顶点数组为 `null`）；或者直接推送原始顶点数据。多边形内部判定相当于不带自相交的 even-odd 而且假设首尾闭合（`math.Polygon.contains()`）。很棘手。

---

EDIT: 内部判定是带自相交情况的 even-odd。

测试数据：`contains(5, 3, [0, 0, 10, 0, 8, 10, 4, 5, 6, 5, 2, 10])`，预期结果：`true`，实际结果：`true`

测试数据：`contains(5, 6, [0, 0, 10, 0, 8, 10, 4, 5, 6, 5, 2, 10])`，预期结果：`false`，实际结果：`false`

数据是这个样子的：

![image](https://cloud.githubusercontent.com/assets/7345875/10055076/dce35030-6266-11e5-9c3f-b1bdc8ae5de7.png)

(5, 3) 明显是在阴影内；虚线相交的地方是 (5, 6)。

---

EDIT2:

Flash的实际结果还没有试验过。设想是这样的：

endfill:=
  if (!is_filling) return
  if (path_closed) calc_triangles_and_fill()
  else calc_raw_windings_and_fill()
closepath:=
  pathclosed = true
lineto,arcto,curveto都将path_closed设为false
最后updategraphics的时候 should_calc_as_closed = closed | is_filling

如果散线（curveto,lineto之后没有closepath）很多，例如弹幕的示例，那么更新的时候计算量就大了（给众人的头发上个色什么的）。

要实现这些功能，就要定义一种中间存储格式，将给定的绘图命令和webgl的状态机连接起来，将要绘制的部分分段：

```
glColor3f(...)
calc_and_draw_polygons()
for parts in graphics_data
  glColor3f(...)
  draw_data(data.indices, data.vertices)
```

另外还没有找到与 `gluTessProperty()` 功能相同的接口……

**Comment by ghost** [comment]
@Hozuki Flash的情形：

![flash1](https://cloud.githubusercontent.com/assets/3143139/10065780/80ce24d0-62bd-11e5-8d1a-c4c80b1aaebb.png)
![flash2](https://cloud.githubusercontent.com/assets/3143139/10065781/81248a32-62bd-11e5-8d71-e2b3a9b7a196.png)

可以看到的几个问题：

之前我把Flash在有填充时的行为搞错了。Flash在有填充的情况下_会_封闭路径。同时，`lineStyle`不应该flush填充数据。需要分离描边和填充这两个state。

earcut虽然很快，但就像它的readme所说，这是以质量为代价的。显然它对自相交的支持并不好。`contains`虽然似乎返回正确的结果，但用它进行逐点光栅化显然需要庞大的运算量，因此不在考虑的范畴。写代码来将输入转换成earcut可接受的形式是一种可能性，但我怀疑这样做的效果并不会比换一个更注重精确性的库，比如earcut的readme中提到的[libtess](https://github.com/brendankenny/libtess.js)，更好，如果假设“从一组顶点数据中寻找hole/将其分为多段来让earcut正确三角化”和“将一组顶点数据正确三角化”需要耗费至少同等的工作的话。libtess实现了`GluTesselator`的API（等效于你在找的`gluTessProperty()`？），并且能够正确地三角化类似于这个测试路径的路径（为了方便在REPL测试，我将`curveTo`更换为了两个`lineTo`）：

```
var verts = [100,100,200,100,200,200,300,200,300,400,180,120];
libtessTriangulate([verts]); // [200,100,180,120,100,100,180,120,200,100,200,166.66666666666669,214.28571428571428,200,200,200,200,166.66666666666669,300,400,214.28571428571428,200,300,200]
earcut(verts).map(function(i) {return [verts[i*2], verts[i*2+1]];}); // (wrong answer) [[180,120],[100,100],[200,100],[200,200],[300,200],[300,400],[300,400],[180,120],[200,100]]
```

当然，如果直接做这样的替换，问题也是很明显的。按照earcut的说法，libtess要比它慢上10倍有余，显然是一个很大的性能冲击。如果有快速的办法仅仅是_检出_自相交而不是_找出_它们，或许可以用这个办法来决定使用哪一个三角化方式。无论如何，这不是仅在这个项目内就能解决的问题。维护一个pixi.js的本地fork是不可避免的了。

**Comment by hozuki** [comment]
@akaza-akari 
是的，应该要重写 `/core/graphics` 下的所有内容。

设想如下：

``` javascript
g.moveTo(...)
g.lineTo(...)
g.beginFill(...)
g.curveTo(...)
g.lineStyle(...)
g.drawCircle(...)
g.endFill()
g.lineTo(...)
// update...
```

对应

``` javascript
// init
g.currentPolyline = createPolyline(...)
g.polylines.push(g.currentPolyline)
// moveTo
g.currentPolyline.moveTo(...)
// lineTo
g.currentPolyline.lineTo(...)
// beginFill
g.currentPolyline = createPolyline(...)
g.polylines.push(g.currentPolyline)
g.isFilling = true
g.fillingPolylines.push(g.currentPolyline)
// curveTo
g.currentPolyline.curveTo(...)
// lineStyle
g.currentPolyline = createPolyline(...)
g.polylines.push(g.currentPolyline)
g.fillingPolylines.push(g.currentPolyline)
// drawCircle
g.currentPolyline.drawCircle(...)
// endFill
g.currentPolyline = createPolyline(...)
g.polylines.push(g.currentPolyline)
g.currentPolygon = createPolygonFromPolylines(g.fillingPolylines)
g.polygons.push(g.currentPolygon)
g.isFilling = false
g.currentPolyline.lineTo(...)
// update
g.renderPolygons(g.polygons)
g.renderPolylines(g.polylines)
```

自然，`createPolyline()`、`createPolygonFromPolylines()` 要保存当前状态，并将push进去的元素状态隔离开。

将边和多边形分离开也可以减少多边形的计算次数，毕竟像示例里有很多复杂的线条但是没有复杂的填充。

在假定用户不会填充过于复杂的多边形的情况下（例，只填充头发，而不是画完后做一次全局填充），libtess还是可以用。[示例](https://brendankenny.github.io/libtess.js/examples/simple_triangulation/index.html)的总时间（三角化+绘制）26ms，考虑图形的复杂度，可以接受。

---

[Clipper](http://sourceforge.net/projects/polyclipping/) 的表现非常优异，可以查看一下其demo。

**Comment by ghost** [comment]
@Hozuki 看起来没问题。

另外，关于之前提到的“在两个三角化方法之间选择”，我找到了这个[stackexchange问答](http://math.stackexchange.com/a/80806)：有一个O(nlogn)的算法可以用来检出自相交。或许可以去找一个实现，然后perf一下看看它是否，并且对于多大的多边形值得一试。运气好的话可以收回一定的性能损失，因为相对来讲没有自相交的图形应该还是多数。

---

EDIT: 我刚刚看到关于Clipper的补充。这并不是一个JS库，所以需要移植或者使用Emscripten之类的工具。demo看起来性能不错，不过我并不能确定从C++移植到JS之后它是否还能这么快……C#版本看起来流畅程度就要稍微差一些。

**Comment by hozuki** [comment]
@akaza-akari [xross](//github.com/Hozuki/xross/) 现在能运行正常测试了。线段有交点而斜率相差很小的情况下，会引发异常，还需要改进。
比较沮丧的是，由于实现上的原因（用 Object 实现了 Map 和 Set 一家子），按照默认配置，线段长度在63左右是个分界点，<63时B-O算法有优势，否则不如用朴素的循环。
（默认：box=1000,segments=1000,segmentLength={length},random=false）
其实这个设置挺极端的了，一般也不会达到这个密度。
写Clipper的时候我大脑短路了……在三角化上没太大帮助（这里重点不是求交而是计算 fill rule），我觉得可以先用 libtess 再说。

**Comment by hozuki** [comment]
@akaza-akari Clipper 在 fill rule 的计算上用的都是对应库的 API，没有自己做实现。

**Comment by ghost** [comment]
@Hozuki 嗯。现在暂且用libtess顶上是一个合适的决定。提升性能是保证结果正确性以后才要做的事情。

按说B-O的时间复杂度要低于朴素法的O(n^2)，所以出现<63这种测试结果确实很奇怪。先修好这边的渲染吧。

**Comment by hozuki** [comment]
@akaza-akari WebGL 实现推上来了。虽说因为 FBO 的原因没有抗锯齿，还有模糊等小问题，但是就画线、填充和正确闭合这个issue来说已经解决了。

**Comment by hozuki** [comment]
@akaza-akari 默认抗锯齿完成，hurray！
